using CLUNL.Data.Layer0.Buffers;
using System.IO;

namespace CLUNL.Data.Layer0
{
    /// <summary>
    /// CommandData which can be used in network in Unity3D.
    /// </summary>
    public struct CommandData : IDataBufferable
    {
        /// <summary>
        /// Command ID
        /// </summary>
        public int Command;
        /// <summary>
        /// External data.
        /// </summary>
        public string Data;
        /// <summary>
        /// CommandData which can be used in network in Unity3D.
        /// </summary>
        /// <param name="Command"></param>
        /// <param name="Data"></param>
        public CommandData(int Command, string Data)
        {
            this.Command = Command;
            this.Data = Data;
        }
        /// <summary>
        /// Convert from DataBuffer
        /// </summary>
        /// <param name="buffer"></param>
        public void Deserialize(DataBuffer buffer)
        {
            Command = buffer.ReadInt();
            Data = buffer.ReadString();
        }
        /// <summary>
        /// Convert to DataBuffer.
        /// </summary>
        /// <returns></returns>
        public DataBuffer Serialize()
        {
            DataBuffer buffer = new DataBuffer();
            buffer.WriteInt(Command);
            buffer.WriteString(Data);
            return buffer;
        }
        /// <summary>
        /// Get string representation.
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return string.Format("{0}|{1}", Command.ToString(), Data);
        }
        /// <summary>
        /// Same as ToString().
        /// </summary>
        /// <param name="D"></param>
        public static implicit operator string(CommandData D)
        {
            return string.Format("{0}|{1}", D.Command.ToString(), D.Data);
        }
        /// <summary>
        /// Same as Serialize().
        /// </summary>
        /// <param name="D"></param>
        public static implicit operator DataBuffer(CommandData D)
        {
            return D.Serialize();
        }
        /// <summary>
        /// Resolve from string generated by ToString().
        /// </summary>
        /// <param name="D"></param>
        public static implicit operator CommandData(string D)
        {
            var i = D.IndexOf('|');
            if (i > 0)
            {
                var C = D.Substring(0, i);
                var CD = D.Substring(i + 1);
                CommandData commandData = new CommandData(int.Parse(C), CD);
                return commandData;
            }
            else
            {
                throw new InvalidDataException();
            }
        }
        /// <summary>
        /// Same as Deserialize
        /// </summary>
        /// <param name="D"></param>
        public static implicit operator CommandData(DataBuffer D)
        {
            CommandData commandData = new CommandData();
            commandData.Deserialize(D);
            return commandData;
        }
    }
}
